version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: hmo-backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    volumes:
      - ./phase2_data:/app/phase2_data
      - ./shared:/app/shared 
      - ./scripts:/app/scripts  
      - ./logs:/app/logs  

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: hmo-frontend
    ports:
      - "8501:8501"
    volumes:
      - ./shared:/app/shared 
    depends_on:
      - backend
